- platform: generic_thermostat
  name: "Heizung Fahrzeughalle Vorne"
  unique_id: "hass.thermostat_heating_front"
  heater: switch.output_heating_front
  target_sensor: sensor.temp_garage_front
  min_temp: 15
  max_temp: 30
  target_temp: 20
  initial_hvac_mode: heat
  target_temp_step: 0.5
  cold_tolerance: 0.5
  hot_tolerance: 0.5

- platform: generic_thermostat
  name: "Heizung Fahrzeughalle Hinten"
  unique_id: "hass.thermostat_heating_back"
  heater: switch.output_heating_back
  target_sensor: sensor.temp_garage_back
  min_temp: 15
  max_temp: 30
  target_temp: 20
  initial_hvac_mode: heat
  target_temp_step: 0.5
  cold_tolerance: 0.5
  hot_tolerance: 0.5