- platform: generic_thermostat
  name: "Heizung Fahrzeughalle Vorne"
  unique_id: "hass.thermostat_heating_front"
  heater: switch.output_heating_front
  target_sensor: sensor.temp_garage_front
  min_temp: 15
  max_temp: 30
  target_temp: 19
  initial_hvac_mode: heat
  target_temp_step: 0.5
  cold_tolerance: 1
  hot_tolerance: 1
  away_temp: 15
  home_temp: 19
  activity_temp: 23

- platform: generic_thermostat
  name: "Heizung Fahrzeughalle Hinten"
  unique_id: "hass.thermostat_heating_back"
  heater: switch.output_heating_back
  target_sensor: sensor.temp_garage_back
  min_temp: 15
  max_temp: 30
  target_temp: 19
  initial_hvac_mode: heat
  target_temp_step: 0.5
  cold_tolerance: 1
  hot_tolerance: 1
  away_temp: 15
  home_temp: 19
  activity_temp: 23

- platform: generic_thermostat
  name: "Heizung Lager"
  unique_id: "hass.thermostat_heating_storage"
  heater: input_boolean.lagerlufterswitch
  target_sensor: sensor.temp_storage_teen
  min_temp: 15
  max_temp: 30
  target_temp: 19
  initial_hvac_mode: heat
  target_temp_step: 0.5
  cold_tolerance: 1
  hot_tolerance: 1
  away_temp: 15
  home_temp: 19
  activity_temp: 23