homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 10.2.1.30/32
      trusted_users:
        10.2.1.30/32: ded5b5cae8b24592aa36bad472ff5b92
  name: FFW
  # Location required to calculate the time the sun rises and sets
  latitude: 49.252909
  longitude: 10.2431055
  country: DE
  elevation: 460
    # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  unit_system: metric
  customize_glob:
    "cover.gate":
      assumed_state: true

homeassistant_alerts:
history:
logbook:
my:
sun:
timer:

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'

mqtt:
  cover: !include gates.yaml
  switch: !include switches.yaml
  sensor: !include sensors.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

climate: !include climates.yaml

logger:
  default: info
  filters:
    homeassistant.components.websocket_api.http.connection:
      - "Error handling message: Unknown error" # Bug in browser_mod

browser_mod:
