homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 10.2.1.30/32
      trusted_users:
        10.2.1.30/32: ded5b5cae8b24592aa36bad472ff5b92
  name: FFW
  # Location required to calculate the time the sun rises and sets
  latitude: 49.252909
  longitude: 10.2431055
  country: DE
  elevation: 460
    # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  unit_system: metric
  customize_glob:
    "cover.gate":
      assumed_state: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/24

homeassistant_alerts:
history:
logbook:
my:
sun:
timer:
media_source:
mobile_app:

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'

mqtt:
  cover: !include gates.yaml
  switch: !include switches.yaml
  sensor: !include sensors.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

climate: !include climates.yaml

logger:
  default: info
  filters:
    homeassistant.components.websocket_api.http.connection:
      - "Error handling message: Unknown error" # Bug in browser_mod

browser_mod:

openid:
  client_id: "hc3h5kBPmsxkA24CPV27xjzm7kHEO7jLbU7xG1EX"
  client_secret: !secret openid_secret
  configure_url: "https://auth.ffw-it.de/application/o/home-assistant-iot/.well-known/openid-configuration"
  username_field: "preferred_username"
  scope: "openid profile email"
  block_login: true
  trusted_ips: # List of CIDR blocks that are not affected by block_login
    - "172.18.0.0/24"
    - "10.2.1.0/24"
  openid_text: "Login with auth.ffw-it.de"
  create_user: false