homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 10.2.1.30/32
      trusted_users:
        10.2.1.30/32: ded5b5cae8b24592aa36bad472ff5b92
  name: FFW
  # Location required to calculate the time the sun rises and sets
  latitude: 49.3
  longitude: 10.2
  country: DE
  elevation: 460
    # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  unit_system: metric
  customize_glob:
    "cover.*":
      assumed_state: true

backup:
counter:
frontend:
homeassistant_alerts:
history:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
logbook:
my:
network:
ssdp:
sun:
system_health:
timer:
webhook:

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'

mqtt:
  cover: !include gates.yaml
  switch: !include switches.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  filters:
    homeassistant.components.websocket_api.http.connection:
      - "Error handling message: Unknown error" # Bug in browser_mod

panel_iframe:
  panel_nodered:
    title: NodeRED
    icon: mdi:nodejs
    url: http://10.2.1.11:1880/
    require_admin: true
  panel_zigbee2mqtt:
    title: Zigbee2MQTT
    icon: mdi:zigbee
    url: http://10.2.1.11:8080/
    require_admin: true

browser_mod:
