---
# OTA (Over The Air) component
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/ota.html
#

ota:
  id: component_ota
  password: !secret ota_password
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5    