homeassistant:
  enabled: true
advanced:
  transmit_power: 20
  channel: 11
  network_key: '!secret network_key'
  log_syslog:
    app_name: Zigbee2MQTT_2
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601
  log_level: debug
serial:
  port: tcp://10.2.1.41:6638
  adapter: zstack
  baudrate: 115200
  disable_led: false
frontend:
  enabled: true
  port: 8081
devices: devices.yaml
mqtt:
  base_topic: zigbee2mqtt_2
  server: mqtt://mqtt
  user: '!secret user'
  password: '!secret password'
  include_device_information: true
availability:
  enabled: true
  active:
    timeout: 10
  passive:
    timeout: 2940
version: 4
