---
# Device: Shelly Plus 2PM 0.1.9 Dual-Core
#
# https://devices.esphome.io/devices/Shelly-Plus-2PM
#
substitutions:
  output_name_1: "Relay 1"
  output_name_2: "Relay 2"
  input_name_1: "Input 1"
  input_name_2: "Input 2"
  max_power: "3600.0"
  max_temp: "80.0"

packages:
  <<: !include_dir_named ../common
  board: !include ../boards/esp32-u4wdh_dual.yaml

binary_sensor:
  - platform: gpio
    id: device_button
    name: "ESPH ${friendly_name} On-Board Button"
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true

  - platform: gpio
    id: "input_1"
    name: "${input_name_1}"
    pin:
      number: GPIO5
      ignore_strapping_warning: true
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    id: "input_2"
    name: "${input_name_2}"
    pin: GPIO18
    filters:
      - delayed_on_off: 50ms

status_led:
  pin:
    number: GPIO0
    ignore_strapping_warning: true
    inverted: true

switch:
  - platform: gpio
    id: "relay_1"
    pin: GPIO12
    name: "${output_name_1} Output"
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: "relay_2"
    pin: GPIO13
    name: "${output_name_2} Output"
    restore_mode: ALWAYS_OFF

sensor:
  # Internal NTC Temperature sensor
  - platform: ntc
    sensor: temp_resistance_reading
    name: "ESPH ${friendly_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    entity_category: 'diagnostic'
    calibration:
      b_constant: 3350
      reference_resistance: 4.7kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: "relay_1"
          - switch.turn_off: "relay_2"
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: "Message from ESPH ${friendly_name}"
              data_template:
                message: "Relays turned off because temperature exceeded ${max_temp}°C"

  # Required for NTC sensor
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 5.6kOhm

  # Required for NTC sensor
  - platform: adc
    id: temp_analog_reading
    pin: GPIO35
    attenuation: 12db
    update_interval: 10s

  - platform: ade7953_i2c
    irq_pin: GPIO27 # Prevent overheating by setting this
    voltage:
      name: "ESPH ${friendly_name} Voltage"
      entity_category: 'diagnostic'
    current_a:
      name: "${output_name_1} Current"
      id: current_channel_1
      entity_category: 'diagnostic'
    current_b:
      name: "${output_name_2} Current"
      id: current_channel_2
      entity_category: 'diagnostic'
    active_power_a:
      name: "${output_name_1} Power"
      id: power_channel_1
      entity_category: 'diagnostic'
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: "relay_1"
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: "Message from ESPH ${friendly_name}"
                data_template:
                  message: "${output_name_1} turned off because power exceeded ${max_power}W"
    active_power_b:
      name: "${output_name_2} Power"
      id: power_channel_2
      entity_category: 'diagnostic'
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: "relay_2"
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: "Message from ESPH ${friendly_name}"
                data_template:
                  message: "${output_name_2} turned off because power exceeded ${max_power}W"
    update_interval: 0.5s
