substitutions:
  system_name: beamer
  friendly_name: Beamer
  device_description: "Beamer power and energy monitoring"
  output_name_1: "Beamer"

packages:
  device: !include devices/shelly_2pm_0.1.9_dual.yaml

binary_sensor:
  - id: !extend input_1
    disabled_by_default: true
  - id: !extend input_2
    disabled_by_default: true

switch:
  - id: !extend relay_1
    restore_mode: RESTORE_DEFAULT_OFF
  - id: !extend relay_2
    disabled_by_default: true
