substitutions:
  system_name: beamer
  friendly_name: Beamer
  device_description: "Beamer power and energy monitoring"
  output_name_1: "Beamer"
  ip4: "36"

packages:
  device: !include devices/shelly_1pm_0.1.9.yaml

binary_sensor:
  - id: !extend input_1
    disabled_by_default: true