substitutions:
  system_name: hmi
  friendly_name: HMI
  device_description: "HMI Ladegeraet"
  output_name_1: "HMI Ladegeraet"

packages:
  device: !include devices/shelly_1_plus.yaml

binary_sensor:
  - id: !extend input_1
    disabled_by_default: true

switch:
  - id: !extend relay_1
    restore_mode: ALWAYS_ON
