# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: false
advanced:
  channel: 25
  network_key: '!secret network_key'

frontend: true

devices: devices.yaml

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://mqtt'
  # MQTT server authentication, uncomment if required:
  user: '!secret user'
  password: '!secret password'
  include_device_information: true

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/zigbee