homeassistant: true
permit_join: false
advanced:
  channel: 25
  network_key: '!secret network_key'
frontend: true
devices: devices.yaml
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
  user: '!secret user'
  password: '!secret password'
  include_device_information: true
serial:
  port: /dev/zigbee
availability: true
